kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  namespace: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

# kubectl apply -f pod.yml
# kubectl get pod -n nginx
# kubectl describe pod/nginx-pod -n nginx
# kubectl exec -it pod/nginx-pod -n nginx -- bash