kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache # works on namespace level
rules:
  - apiGroups: ["*"] # apply to all api groups
    resources: ["deployments","pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
