kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: mysql
spec:
  clusterIP: None # This is a headless service, only for internal communication and no external access.
  selector:
    app: mysql # name of the pod which we want to expose
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306